# Get the Data

In [1]:
import pandas as pd
data = pd.read_csv("https://github.com/CAWaterBoardDataCenter/DDW-Drought-Priortization-2022/raw/main/DroughtWatchPrioritization_v9_input_data.csv", header =0)

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 35 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [3]:
data["DroughtExperienced"].value_counts()

0    2710
1     156
Name: DroughtExperienced, dtype: int64

In [4]:
# Common imports
import numpy as np
import os

In [5]:
# Separate input features and target
data_labels = data["DroughtExperienced"]

# Dropping not needed columns
data = data.drop(["DroughtExperienced"], axis=1)


In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 34 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [7]:
data_labels

0       0
1       0
2       0
3       0
4       0
       ..
2861    0
2862    0
2863    0
2864    0
2865    0
Name: DroughtExperienced, Length: 2866, dtype: int64

In [8]:
data_num = data.select_dtypes(include=[np.number])

Now let's drop some outliers:

In [9]:
#from sklearn.ensemble import IsolationForest

#isolation_forest = IsolationForest(random_state=42)
#outlier_pred = isolation_forest.fit_predict(data_num)

In [10]:
#outlier_pred

In [11]:
#data = data.iloc[outlier_pred == 1]
#data_labels = data_labels.iloc[outlier_pred == 1]

In [12]:
#data.info()

In [13]:
#data_labels

In [14]:
data_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ServiceConnections        2866 non-null   int64  
 1   Population                2866 non-null   int64  
 2   Score_SourceNumber        2866 non-null   float64
 3   CDAG_rank                 2866 non-null   int64  
 4   Score_1702                2866 non-null   int64  
 5   Score_1705                2866 non-null   int64  
 6   Score_1706                2866 non-null   int64  
 7   Score_1812                2866 non-null   int64  
 8   Score_1813                2866 non-null   int64  
 9   Score_1814                2866 non-null   int64  
 10  Score_1815                2866 non-null   int64  
 11  EAR2020DroughtRiskScore   2866 non-null   int64  
 12  SAFER_AccessibilityScore  2866 non-null   float64
 13  Lat                       2866 non-null   float64
 14  Long    

In [15]:
data_cat = data.select_dtypes(include=[np.object])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [16]:
data_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 16 columns):
 #   Column                                       Non-Null Count  Dtype 
---  ------                                       --------------  ----- 
 0   Score_SourceCapacityViolations               2866 non-null   object
 1   Score_SCM                                    2866 non-null   object
 2   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object
 3   Curtailment                                  2866 non-null   object
 4   County                                       2866 non-null   object
 5   CurtailedWatershed                           2866 non-null   object
 6   HUC4                                         2866 non-null   object
 7   HUC8                                         2866 non-null   object
 8   Basin_Number_part1                           2866 non-null   object
 9   FracturedRock                                2866 non-null   object
 10  Basin12     

In [17]:
from sklearn.compose import ColumnTransformer
num_attribs = list(data_num)

cat_attribs = list(data_cat)


In [18]:
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import OneHotEncoder

full_pipeline = ColumnTransformer([
        ("num", StandardScaler(), num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

data_prepared = full_pipeline.fit_transform(data)
data_prepared

<2866x495 sparse matrix of type '<class 'numpy.float64'>'
	with 97444 stored elements in Compressed Sparse Row format>

In [19]:
data_labels

0       0
1       0
2       0
3       0
4       0
       ..
2861    0
2862    0
2863    0
2864    0
2865    0
Name: DroughtExperienced, Length: 2866, dtype: int64

In [20]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X, y = sm.fit_resample(data_prepared, data_labels)
X.shape, y.shape

((5420, 495), (5420,))

In [21]:
y = pd.DataFrame(y, columns = ['DroughtExperienced'])
y.DroughtExperienced.value_counts()

0    2710
1    2710
Name: DroughtExperienced, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
#X_train, X_test = train_test_split(
#    X, test_size=0.2,  random_state=42)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, \
                                                    y, \
                                                    test_size=0.2,
                                                   random_state=42)

In [24]:
X_train

<4336x495 sparse matrix of type '<class 'numpy.float64'>'
	with 155198 stored elements in Compressed Sparse Row format>

In [25]:
X_test

<1084x495 sparse matrix of type '<class 'numpy.float64'>'
	with 38761 stored elements in Compressed Sparse Row format>

In [26]:
#y_train, y_test = train_test_split(
#    y, test_size=0.2,  random_state=42)

In [27]:
y_train

DroughtExperienced
3032                   1
1231                   0
1586                   0
4676                   1
1370                   0
...                  ...
3772                   1
5191                   1
5226                   1
5390                   1
860                    0

[4336 rows x 1 columns]

In [28]:
y_test

DroughtExperienced
4417                   1
1538                   0
315                    0
297                    0
4946                   1
...                  ...
75                     0
1776                   0
2981                   1
3648                   1
3895                   1

[1084 rows x 1 columns]

# MLP Classifier

In [67]:
from sklearn.neural_network import MLPClassifier

#iris = load_iris()
#X_train_full, X_test, y_train_full, y_test = train_test_split(
#    iris.data, iris.target, test_size=0.1, random_state=42)
#X_train, X_valid, y_train, y_valid = train_test_split(
#   X_train_full, y_train_full, test_size=0.1, random_state=42)

mlp_clf = MLPClassifier(hidden_layer_sizes=[100], max_iter=10_000,
                        random_state=42)
#pipeline = make_pipeline(StandardScaler(), mlp_clf)
mlp_clf.fit(X_train, y_train.values.ravel())
#accuracy = mlp_clf.score(X_valid, y_valid)
#accuracy

MLPClassifier(hidden_layer_sizes=[100], max_iter=10000, random_state=42)

In [68]:
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.metrics import f1_score


skfolds = StratifiedKFold(n_splits=10)  # add shuffle=True if the dataset is not
                                       # already shuffled
for train_index, test_index in skfolds.split(X_train, y_train.values.ravel()):
    clone_clf = clone(mlp_clf)
    X_train_folds = X_train[train_index]
    y_train_folds = y_train.values.ravel()[train_index]
    X_test_fold = X_train[test_index]
    y_test_fold = y_train.values.ravel()[test_index]

    clone_clf.fit(X_train_folds, y_train_folds)
    y_pred = clone_clf.predict(X_test_fold)
    #n_correct = sum(y_pred == y_test_fold)
    #print(n_correct / len(y_pred))
    print(f1_score(y_test_fold, y_pred))

0.9864864864864865
0.9711751662971174
0.9690265486725663
0.9887133182844243
0.9775784753363228
0.9819819819819819
0.9730941704035874
0.9732142857142857
0.9909090909090909
0.9752808988764046


In [69]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(mlp_clf, X_train, y_train.values.ravel(), cv=10)

In [70]:
import numpy
unique, counts = numpy.unique(y_train_pred, return_counts=True)
dict(zip(unique, counts))

{0: 2061, 1: 2275}

In [71]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train, y_train_pred)
cm

array([[2059,   93],
       [   2, 2182]])

In [72]:
from sklearn.metrics import f1_score

f1_score(y_train, y_train_pred)

0.9786947746131419

# Stochastic Gradient Descent Classifier (SGDC)

In [58]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42, loss='log')
sgd_clf.fit(X_train, y_train.values.ravel())

SGDClassifier(loss='log', random_state=42)

In [60]:
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.metrics import f1_score


skfolds = StratifiedKFold(n_splits=10)  # add shuffle=True if the dataset is not
                                       # already shuffled
for train_index, test_index in skfolds.split(X_train, y_train.values.ravel()):
    clone_clf = clone(sgd_clf)
    X_train_folds = X_train[train_index]
    y_train_folds = y_train.values.ravel()[train_index]
    X_test_fold = X_train[test_index]
    y_test_fold = y_train.values.ravel()[test_index]

    clone_clf.fit(X_train_folds, y_train_folds)
    y_pred = clone_clf.predict(X_test_fold)
    #n_correct = sum(y_pred == y_test_fold)
    #print(n_correct / len(y_pred))
    print(f1_score(y_test_fold, y_pred))

0.9090909090909091
0.9217758985200846
0.8952772073921971
0.8888888888888888
0.9237472766884532
0.908256880733945
0.8944954128440367
0.8764044943820225
0.9339407744874715
0.9220489977728284


In [61]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf, X_train, y_train.values.ravel(), cv=10)

In [62]:
import numpy
unique, counts = numpy.unique(y_train_pred, return_counts=True)
dict(zip(unique, counts))

{0: 1970, 1: 2366}

In [63]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train, y_train_pred)
cm

array([[1850,  302],
       [ 120, 2064]])

In [64]:
from sklearn.metrics import f1_score

f1_score(y_train, y_train_pred)

0.9072527472527473

# SVC - F1 = 0.977

In [51]:
from sklearn.svm import SVC

poly_kernel_svm_clf = SVC(kernel="poly", degree=3, coef0=1, C=5, probability =True)

poly_kernel_svm_clf.fit(X_train, y_train.values.ravel())

SVC(C=5, coef0=1, kernel='poly', probability=True)

In [52]:
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.metrics import f1_score


skfolds = StratifiedKFold(n_splits=10)  # add shuffle=True if the dataset is not
                                       # already shuffled
for train_index, test_index in skfolds.split(X_train, y_train.values.ravel()):
    clone_clf = clone(poly_kernel_svm_clf)
    X_train_folds = X_train[train_index]
    y_train_folds = y_train.values.ravel()[train_index]
    X_test_fold = X_train[test_index]
    y_test_fold = y_train.values.ravel()[test_index]

    clone_clf.fit(X_train_folds, y_train_folds)
    y_pred = clone_clf.predict(X_test_fold)
    #n_correct = sum(y_pred == y_test_fold)
    #print(n_correct / len(y_pred))
    print(f1_score(y_test_fold, y_pred))

0.9797752808988764
0.9733333333333333
0.9690265486725663
0.9842696629213482
0.9775784753363228
0.9775784753363228
0.9753914988814317
0.9774774774774776
0.9886621315192743
0.96875


In [53]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(poly_kernel_svm_clf, X_train, y_train.values.ravel(), cv=10)

In [54]:
import numpy
unique, counts = numpy.unique(y_train_pred, return_counts=True)
dict(zip(unique, counts))

{0: 2056, 1: 2280}

In [55]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train, y_train_pred)
cm

array([[2053,   99],
       [   3, 2181]])

In [56]:
from sklearn.metrics import f1_score

f1_score(y_train, y_train_pred)

0.9771505376344087

# Random Forest - F1 = 0.979

In [33]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier(n_estimators=1000, 
                            n_jobs=-1, random_state=42)

forest_clf.fit(X_train, y_train.values.ravel())

RandomForestClassifier(n_estimators=1000, n_jobs=-1, random_state=42)

In [34]:
from sklearn.model_selection import cross_val_score

cross_val_score(forest_clf, X_train, y_train.values.ravel(), cv=10, scoring="f1_macro")

array([0.96082929, 0.97925728, 0.96312111, 0.98617394, 0.97004592,
       0.98617247, 0.9769042 , 0.98613956, 0.99307145, 0.98383337])

In [35]:
from sklearn.model_selection import StratifiedKFold
from sklearn.base import clone
from sklearn.metrics import f1_score


skfolds = StratifiedKFold(n_splits=10)  # add shuffle=True if the dataset is not
                                       # already shuffled
for train_index, test_index in skfolds.split(X_train, y_train.values.ravel()):
    clone_clf = clone(forest_clf)
    X_train_folds = X_train[train_index]
    y_train_folds = y_train.values.ravel()[train_index]
    X_test_fold = X_train[test_index]
    y_test_fold = y_train.values.ravel()[test_index]

    clone_clf.fit(X_train_folds, y_train_folds)
    y_pred = clone_clf.predict(X_test_fold)
    #n_correct = sum(y_pred == y_test_fold)
    #print(n_correct / len(y_pred))
    print(f1_score(y_test_fold, y_pred))

0.9607390300230946
0.979591836734694
0.9638009049773755
0.9863013698630136
0.9701149425287356
0.9863636363636363
0.9767441860465116
0.9863636363636363
0.9931034482758622
0.9839080459770114


In [36]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(forest_clf, X_train, y_train.values.ravel(), cv=10)

In [37]:
import numpy
unique, counts = numpy.unique(y_train_pred, return_counts=True)
dict(zip(unique, counts))

{0: 2151, 1: 2185}

In [38]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train, y_train_pred)
cm

array([[2105,   47],
       [  46, 2138]])

Cross validation F1 = 

In [39]:
from sklearn.metrics import f1_score

f1_score(y_train, y_train_pred)

0.9787136644541085

In [40]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [41]:
forest_clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 1000,
 'n_jobs': -1,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [42]:

param_distribs = {'random_forest__max_features': randint(low=1, high=22)}


In [49]:
rnd_search = RandomizedSearchCV(
    forest_clf, param_distributions=param_distribs, n_iter=20, cv=10,
    scoring='f1_macro', random_state=42)

#rnd_search.fit(X_train)

Predict the test set - F1 = 0.978

In [ ]:
y_test_pred = forest_clf.predict(X_test)

In [ ]:
y_test_prob = forest_clf.predict_proba(X_test)

In [ ]:
cm = confusion_matrix(y_test, y_test_pred)

In [ ]:
cm

array([[549,   9],
       [ 14, 512]])

In [ ]:
f1_score(y_test, y_test_pred)

0.9780324737344793

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, y_test_pred)

0.973384030418251

#  Predict the entire set - F1 = 0.935

In [ ]:
data_prepared

<2866x476 sparse matrix of type '<class 'numpy.float64'>'
	with 83114 stored elements in Compressed Sparse Row format>

In [ ]:
predictions = forest_clf.predict(data_prepared)

In [ ]:
probabilities = forest_clf.predict_proba(data_prepared)

In [ ]:
cm = confusion_matrix(data_labels, predictions)
cm

array([[2701,    9],
       [  11,  145]])

In [ ]:
#from sklearn.metrics import recall_score
recall_score(data_labels, predictions)

0.9294871794871795

In [ ]:
f1_score(data_labels, predictions)

0.9354838709677419

In [ ]:
data_labels

0       0
1       0
2       0
3       0
4       0
       ..
2861    0
2862    0
2863    0
2864    0
2865    0
Name: DroughtExperienced, Length: 2866, dtype: int64

In [ ]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
predictions.shape

(2866,)

In [ ]:
data.shape

(2866, 29)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 29 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [ ]:
probabilities.shape

(2866, 2)

In [ ]:
probabilities

array([[0.99, 0.01],
       [1.  , 0.  ],
       [0.98, 0.02],
       ...,
       [0.97, 0.03],
       [0.9 , 0.1 ],
       [0.99, 0.01]])

In [ ]:
s1 = pd.DataFrame(predictions)
s1.index = data.index # its important for comparison
s1.columns = ["MyPredictions"]
s2 = pd.DataFrame(probabilities)
s2.index = data.index # its important for comparison
s2.columns = ["Prob_A","Prob_B"]
results = pd.concat([data, s1, s2], axis=1)

In [ ]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 32 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [ ]:
results.to_csv("RF_prediction_results.csv")

In [ ]:
from google.colab import files
files.download("RF_prediction_results.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>