# Get the Data

In [ ]:
import pandas as pd
data = pd.read_csv("https://github.com/CAWaterBoardDataCenter/DDW-Drought-Priortization-2022/raw/main/DroughtWatchPrioritization_v9_input_data.csv", header =0)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 35 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [ ]:
data["DroughtExperienced"].value_counts()

0    2710
1     156
Name: DroughtExperienced, dtype: int64

In [ ]:
# Common imports
import numpy as np
import os

In [ ]:
# Separate input features and target
data_labels = data["DroughtExperienced"]

# Dropping not needed columns
data = data.drop(["DroughtExperienced"], axis=1)


In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 34 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [ ]:
data_labels

0       0
1       0
2       0
3       0
4       0
       ..
2861    0
2862    0
2863    0
2864    0
2865    0
Name: DroughtExperienced, Length: 2866, dtype: int64

In [ ]:
data_num = data.select_dtypes(include=[np.number])

Now let's drop some outliers:

In [ ]:
#from sklearn.ensemble import IsolationForest

#isolation_forest = IsolationForest(random_state=42)
#outlier_pred = isolation_forest.fit_predict(data_num)

In [ ]:
#outlier_pred

array([ 1,  1,  1, ..., -1, -1,  1])

In [ ]:
#data = data.iloc[outlier_pred == 1]
#data_labels = data_labels.iloc[outlier_pred == 1]

In [ ]:
#data.info()

In [ ]:
#data_labels

0       0
1       0
2       0
3       0
4       0
       ..
2861    0
2862    0
2863    0
2864    0
2865    0
Name: DroughtExperienced, Length: 2866, dtype: int64

In [ ]:
data_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ServiceConnections        2866 non-null   int64  
 1   Population                2866 non-null   int64  
 2   Score_SourceNumber        2866 non-null   float64
 3   CDAG_rank                 2866 non-null   int64  
 4   Score_1702                2866 non-null   int64  
 5   Score_1705                2866 non-null   int64  
 6   Score_1706                2866 non-null   int64  
 7   Score_1812                2866 non-null   int64  
 8   Score_1813                2866 non-null   int64  
 9   Score_1814                2866 non-null   int64  
 10  Score_1815                2866 non-null   int64  
 11  EAR2020DroughtRiskScore   2866 non-null   int64  
 12  SAFER_AccessibilityScore  2866 non-null   float64
 13  Lat                       2866 non-null   float64
 14  Long    

In [ ]:
data_cat = data.select_dtypes(include=[np.object])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [ ]:
data_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 15 columns):
 #   Column                                       Non-Null Count  Dtype 
---  ------                                       --------------  ----- 
 0   Score_SourceCapacityViolations               2866 non-null   object
 1   Score_SCM                                    2866 non-null   object
 2   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object
 3   Curtailment                                  2866 non-null   object
 4   County                                       2866 non-null   object
 5   CurtailedWatershed                           2866 non-null   object
 6   HUC8                                         2866 non-null   object
 7   Basin_Number_part1                           2866 non-null   object
 8   FracturedRock                                2866 non-null   object
 9   Basin12                                      2866 non-null   object
 10  Basin34     

In [ ]:
from sklearn.compose import ColumnTransformer
num_attribs = list(data_num)

cat_attribs = list(data_cat)


In [ ]:
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import OneHotEncoder

full_pipeline = ColumnTransformer([
        ("num", StandardScaler(), num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

data_prepared = full_pipeline.fit_transform(data)
data_prepared

<2866x476 sparse matrix of type '<class 'numpy.float64'>'
	with 83114 stored elements in Compressed Sparse Row format>

In [ ]:
data_labels

0       0
1       0
2       0
3       0
4       0
       ..
2861    0
2862    0
2863    0
2864    0
2865    0
Name: DroughtExperienced, Length: 2866, dtype: int64

In [ ]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X, y = sm.fit_resample(data_prepared, data_labels)
X.shape, y.shape

((5420, 476), (5420,))

In [ ]:
y = pd.DataFrame(y, columns = ['DroughtExperienced'])
y.DroughtExperienced.value_counts()

0    2710
1    2710
Name: DroughtExperienced, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
#X_train, X_test = train_test_split(
#    X, test_size=0.2,  random_state=42)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, \
                                                    y, \
                                                    test_size=0.2,
                                                   random_state=42)

In [ ]:
X_train

<4336x476 sparse matrix of type '<class 'numpy.float64'>'
	with 132785 stored elements in Compressed Sparse Row format>

In [ ]:
X_test

<1084x476 sparse matrix of type '<class 'numpy.float64'>'
	with 33168 stored elements in Compressed Sparse Row format>

In [ ]:
#y_train, y_test = train_test_split(
#    y, test_size=0.2,  random_state=42)

In [ ]:
y_train

DroughtExperienced
3032                   1
1231                   0
1586                   0
4676                   1
1370                   0
...                  ...
3772                   1
5191                   1
5226                   1
5390                   1
860                    0

[4336 rows x 1 columns]

In [ ]:
y_test

DroughtExperienced
4417                   1
1538                   0
315                    0
297                    0
4946                   1
...                  ...
75                     0
1776                   0
2981                   1
3648                   1
3895                   1

[1084 rows x 1 columns]

# Random Forest - F1 = 0.978

In [ ]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier(random_state=42)

forest_clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestClassifier(random_state=42)

In [ ]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(forest_clf, X_train, y_train, cv=3)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train, y_train_pred)
cm

array([[2099,   53],
       [  44, 2140]])

Cross validation F1 = 0.971

In [ ]:
from sklearn.metrics import f1_score

f1_score(y_train, y_train_pred)

0.9778387023075166

Predict the test set - F1 = 0.978

In [ ]:
y_test_pred = forest_clf.predict(X_test)

In [ ]:
y_test_prob = forest_clf.predict_proba(X_test)

In [ ]:
cm = confusion_matrix(y_test, y_test_pred)

In [ ]:
cm

array([[549,   9],
       [ 14, 512]])

In [ ]:
f1_score(y_test, y_test_pred)

0.9780324737344793

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, y_test_pred)

0.973384030418251

#  Predict the entire set - F1 = 0.935

In [ ]:
data_prepared

<2866x476 sparse matrix of type '<class 'numpy.float64'>'
	with 83114 stored elements in Compressed Sparse Row format>

In [ ]:
predictions = forest_clf.predict(data_prepared)

In [ ]:
probabilities = forest_clf.predict_proba(data_prepared)

In [ ]:
cm = confusion_matrix(data_labels, predictions)
cm

array([[2701,    9],
       [  11,  145]])

In [ ]:
#from sklearn.metrics import recall_score
recall_score(data_labels, predictions)

0.9294871794871795

In [ ]:
f1_score(data_labels, predictions)

0.9354838709677419

In [ ]:
data_labels

0       0
1       0
2       0
3       0
4       0
       ..
2861    0
2862    0
2863    0
2864    0
2865    0
Name: DroughtExperienced, Length: 2866, dtype: int64

In [ ]:
predictions

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
predictions.shape

(2866,)

In [ ]:
data.shape

(2866, 29)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 29 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [ ]:
probabilities.shape

(2866, 2)

In [ ]:
probabilities

array([[0.99, 0.01],
       [1.  , 0.  ],
       [0.98, 0.02],
       ...,
       [0.97, 0.03],
       [0.9 , 0.1 ],
       [0.99, 0.01]])

In [ ]:
s1 = pd.DataFrame(predictions)
s1.index = data.index # its important for comparison
s1.columns = ["MyPredictions"]
s2 = pd.DataFrame(probabilities)
s2.index = data.index # its important for comparison
s2.columns = ["Prob_A","Prob_B"]
results = pd.concat([data, s1, s2], axis=1)

In [ ]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2866 entries, 0 to 2865
Data columns (total 32 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   ServiceConnections                           2866 non-null   int64  
 1   Population                                   2866 non-null   int64  
 2   Score_SourceNumber                           2866 non-null   float64
 3   Score_SourceCapacityViolations               2866 non-null   object 
 4   Score_SCM                                    2866 non-null   object 
 5   Score_CriticallyOverdraftedGroundwaterBasin  2866 non-null   object 
 6   CDAG_rank                                    2866 non-null   int64  
 7   Curtailment                                  2866 non-null   object 
 8   Score_1702                                   2866 non-null   int64  
 9   Score_1705                                   2866 non-null   int64  
 10  

In [ ]:
results.to_csv("RF_prediction_results.csv")

In [ ]:
from google.colab import files
files.download("RF_prediction_results.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>